# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
import itertools
import os 
import glob
import sys
import pandas as pd

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/01_readqc.smk"
include: "rules/02_readanalysis.smk"
include: "rules/03_assembly.smk"
include: "rules/04_binning.smk"
include: "rules/05_contiganalysis.smk"

rule all:
    input:
        get_rules